version: '3.4'

services:
  app:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn sr start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate

  server:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn srv start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate
    ports:
      - "${SERVER_PORT}:80"

  web:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn web watch
    depends_on:
      - server

  migrate:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    command: yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
version: '3.4'

services:
  app:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn sr start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate

  server:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn srv start
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    depends_on:
      - migrate
    ports:
      - "${SERVER_PORT}:80"

  web:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    command: yarn web watch
    depends_on:
      - server

  migrate:
    image: "monorepo-node-app"
    volumes:
      - ./app:/srv
    environment:
      - DATABASE_URL=postgres://app:app@db/app
    command: yarn db-migrate up
    depends_on:
      - db

  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: app
      POSTGRES_USER: app
